name: Attach Results to Pull Request

on:
  workflow_dispatch:

jobs:
  attach-results:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "charanv@devtoolsin"
        git config --global user.name "Charan-SV"

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run your workflow or commands
      run: |
        # Replace this with the commands you want to execute.
        echo "This is your workflow output" > results.txt

    - name: Create a temporary branch to commit the results
      run: |
        git checkout -b temp-branch
        git add results.txt
        git commit -m "Add results.txt"
        git push origin temp-branch

    - name: Create a pull request
      run: |
        gh pr create --base main --head temp-branch --title "Results" --body "Here are the results of the workflow:" --reviewer Charan-SV

    - name: Get Pull Request URL
      id: pr_url
      run: |
        PR_URL=$(gh pr list -B main -H temp-branch --json html_url --jq .[0].html_url)
        echo "Pull Request URL: $PR_URL"

    - name: Cleanup
      run: |
        git push origin --delete temp-branch
