name: Attach Results to Pull Request

on:
  workflow_dispatch:

jobs:
  attach-results:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run your workflow or commands
      run: |
        # Replace this with the commands you want to execute.
        echo "This is your workflow output" > results.txt

    - name: Attach results to pull request
      run: |
        # Create a temporary branch to commit the results
        git checkout -b temp-branch
        git add results.txt
        git commit -m "Add results.txt"
        git push origin temp-branch

        # Create a pull request
        PR_URL=$(curl -s -X POST \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -d "{\"title\":\"Results\",\"base\":\"main\",\"head\":\"temp-branch\",\"body\":\"Here are the results of the workflow:\n\n$(cat results.txt)\"}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls" | jq -r .html_url)

        echo "Pull Request URL: $PR_URL"

    - name: Cleanup
      run: |
        # Delete the temporary branch
        git push origin --delete temp-branch
