name: Attach results.txt to Pull Request
on: pull_request
jobs:
  attach-results:
    name: Attach results.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create output directory
        run: mkdir -p output/
      
      - name: Generate results.txt
        run: echo "This is a fancy comment" > output/results.txt
      
      - name: Upload results.txt as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: output
      
      - name: Attach results.txt to Pull Request
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: output/results.txt
      
      - name: Post PR Comment with attachment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('output/results.txt', 'utf8');
            const github = context.repo;
            const prNumber = context.issue.number;
            github.issues.createComment({ issue_number: prNumber, owner: github.owner, repo: github.repo, body: content });
