name: Attach Results to Pull Request

on:
  workflow_dispatch:

jobs:
  attach-results:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Create the output directory
      run: mkdir -p $GITHUB_WORKSPACE/output

    - name: Run your workflow or commands
      run: |
        # Replace this with the commands you want to execute.
        echo "This is your workflow output" > $GITHUB_WORKSPACE/output/results.txt

    - name: Upload results to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: $GITHUB_WORKSPACE/output/results.txt
