name: Attach results.txt to Pull Request
on: pull_request
jobs:
  attach-results:
    name: Attach results.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create output directory
        run: mkdir -p output/
      
      - name: Generate results.txt
        run: echo "This is a fancy comment" > output/results.txt
      
      - name: Upload results.txt as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: output/
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install requests library
        run: pip install requests
      
      - name: Create GitHub Personal Access Token
        id: create-token
        run: echo "::set-output name=token::$(curl -X POST -u ${{ secrets.GITHUB_USERNAME }}:${{ secrets.GITHUB_TOKEN }} https://api.github.com/authorizations -d '{"scopes":["repo"], "note":"PR Comment Upload"}' | jq -r '.token')"
      
      - name: Upload results.txt as a comment
        run: |
          COMMENT="results.txt attachment"
          FILENAME="output/results.txt"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          TOKEN="${{ steps.create-token.outputs.token }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
          UPLOAD_URL=$(curl -X POST -H "Authorization: token $TOKEN" "$API_URL" -d '{"body":"'"$COMMENT"'"}' | jq -r '.url')
          curl -X POST -H "Authorization: token $TOKEN" -H "Content-Type: $(file -b --mime-type "$FILENAME")" --data-binary @"$FILENAME" "$UPLOAD_URL"
    
